apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "vault-configuration"
spec:
  organization: "this-is-defined-at-the-cluster-level-for-your-organization"
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/GlueOps/terraform-vault-configuration.git"
  variables:
    - key: RUN_DEPLOYMENT_NUMBER
      sensitive: false
      value: "{{ .Values.RUN_DEPLOYMENT_NUMBER }}"
      environmentVariable: true
    - key: GLUEOPS_ENV
      sensitive: false
      value: "{{ .Values.GLUEOPS_ENV }}"
      environmentVariable: false
