apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "vault-configuration"
spec:
  organization: "{{ .Values.TFC_ORG_NAME }}"
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/GlueOps/terraform-vault-configuration.git"
  variables:
    - key: TOGGLE_TO_RERUN
      sensitive: false
      value: "{{ .Values.TOGGLE_TO_RERUN }}"
      environmentVariable: true
    - key: GLUEOPS_ENV
      sensitive: false
      value: "{{ .Values.GLUEOPS_ENV }}"
      environmentVariable: false
